export const code21 =
`import type { Metadata } from "next";
import BootstrapClient from '@/components/bootstrap-client';

export const metadata: Metadata = {
    title: 'Next.js application',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                {children}
                <BootstrapClient/>
            </body>
        </html>
    );
}`;