export const code1 = `
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Next.js application',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
`;