export const code7 = `
import type { Metadata } from "next";

// This is how we globally import Bootstrap CSS
import 'bootstrap/dist/css/bootstrap.min.css';

import {
    // ClerkProvider component provides our pages and components with a user if the latter is authenticated.
    ClerkProvider,

    /* SignedOut component will only display its contents if no user is authenticated.
    Here, it will display a button to sign in (SignInButton) and a button to sign up (SignUpButton). */
    SignedOut,
    SignInButton,
    SignUpButton,

    /* SignedIn component does the opposite of SignedOut component, i.e., if a user is authenticated, it will display its content. 
    Here, we'll have a button (UserButton) that lets you either manage your user account or sign out. */
    SignedIn,
    UserButton,
} from '@clerk/nextjs';

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <header>
                        <SignedOut>
                            <SignInButton />
                            <SignUpButton />
                        </SignedOut>
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </header>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
`;