import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import './globals.css';
import { type Metadata } from 'next'
import Header from '@/components/header';
import Footer from '@/components/footer';
import Script from 'next/script';

export const metadata: Metadata = {
  	title: 'Gidmi',
  	description: 'Generated by create next app',
}

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode
}>) {
  	return (
        <html lang="en">
            <head>
                <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9490135232409415" crossOrigin="anonymous"></Script>
            </head>
            <body className='bg-dark'>
                <Header/>
                {children}
                <Footer/>
            </body>
        </html>
  	)
}